#端口信息
server:
  port: 8080
  servlet:
    context-path: /orm


spring:
  #数据库链接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    password: 123456
    username: root
  redis:
    port: 6379
    database: 0
    host: 127.0.0.1
    connect-timeout: 1000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        min-idle: 0



#日志文件
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  config: classpath:log/logback-spring.xml
